import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * Arbitrary Tailwind *values* — `bg-[#0af]`, `p-[13px]`, `text-[11px]` — are
 * the hole in a token system. The two-layer design in app/globals.css already
 * makes the raw colour ramps unreachable by keeping them out of `@theme`, but
 * nothing stops someone typing a literal. This closes that.
 *
 * Scoped deliberately:
 *
 * - **Only design properties.** The prefixes below are the ones that carry
 *   colour, spacing and type. Structural escapes stay legal, because they are
 *   not design decisions and have no token to reach for: `transition-[...]` is
 *   a property list, `grid-cols-[repeat(...)]` is a layout algorithm,
 *   `content-['·']` is a string, and `data-[state=open]:` is a variant.
 * - **Arbitrary values, not arbitrary variants.** The negative lookahead on
 *   `:` is what separates `bg-[#0af]` from `data-[state=open]:bg-primary`.
 * - **Our code only.** `components/ui/**` is vendored shadcn, regenerated by
 *   `shadcn add`, and full of legitimate internals like
 *   `h-[calc(100%-1px)]`. Linting it would mean either a permanently failing
 *   build or a fork we have to maintain by hand.
 *
 * If a value here has no token, the fix is to add a role or a scale step in
 * globals.css — not to reach past this rule.
 */
const DESIGN_PREFIXES = [
  "text",
  "bg",
  "border",
  "rounded",
  "shadow",
  "leading",
  "tracking",
  "font",
  "p",
  "px",
  "py",
  "pt",
  "pb",
  "pl",
  "pr",
  "m",
  "mx",
  "my",
  "mt",
  "mb",
  "ml",
  "mr",
  "w",
  "h",
  "size",
  "min-w",
  "min-h",
  "max-w",
  "max-h",
  "gap",
  "top",
  "bottom",
  "left",
  "right",
  "inset",
  "fill",
  "stroke",
  "opacity",
  "duration",
  "ease",
].join("|");

// `(?!:)` keeps arbitrary variants (`data-[state=open]:`) legal; only values
// are matched.
//
// Escaping is single-level on purpose: esquery reads the regex source straight
// out of the selector string, so `\\s` here becomes `\s` in the pattern. An
// extra pair — the obvious first guess — compiles to a literal backslash and
// the rule then silently matches nothing.
const ARBITRARY_VALUE = `(^|\\s)-?(${DESIGN_PREFIXES})-\\[[^\\]]+\\](?!:)`;

const message =
  "Arbitrary Tailwind value. Use a design token — see docs/design-system.md. " +
  "If no token fits, add a semantic role or scale step in app/globals.css " +
  "rather than reaching past the token layer.";

/**
 * "No inline subscription checks, ever" (ADR-0006) is a wish until something
 * enforces it. This is the something.
 *
 * The catalog and the study area are both large surfaces, and the fourth
 * inline check gets written at 6pm on a Friday by someone who has not read the
 * ADR. A rule stops it; a convention does not. Same reasoning as
 * `tests/unit/tokens.test.ts` and `tests/e2e/contrast.spec.ts`, which enforce
 * design decisions by tooling rather than by memory.
 *
 * **What it matches, and what it deliberately does not.** Any read of a
 * `subscriptionStatus` property — `profile.subscriptionStatus`,
 * `viewer?.subscriptionStatus`, a `{ subscriptionStatus }` destructure — plus
 * the snake_case column name, which is how the same check gets written in raw
 * SQL. Passing a whole `profile` to `canAccess` is untouched, because that is
 * the sanctioned path: the boundary reads the field, nobody else does.
 *
 * `lib/entitlement/**` is exempt — it *is* the boundary. That is the only
 * exemption, and it should stay the only one: a display of the current status
 * looks identical to a gate at the syntax level, so the moment a second
 * directory is allowed to read the column the rule stops meaning anything.
 * `describeToggleState` in `lib/entitlement/dev-toggle.ts` exists precisely so
 * the debug panel can render the value without needing an exemption.
 */
const subscriptionMessage =
  "Inline subscription check. Access is decided by canAccess() in " +
  "lib/entitlement/can-access.ts and nowhere else — see ADR-0006. Pass the " +
  "profile to the boundary and render what it returns, rather than reading " +
  "subscription status here.";

const subscriptionSelectors = [
  // profile.subscriptionStatus / viewer?.subscriptionStatus
  'MemberExpression > Identifier[name="subscriptionStatus"]',
  // const { subscriptionStatus } = profile
  'ObjectPattern > Property > Identifier[name="subscriptionStatus"]',
  // The Drizzle column and raw SQL both spell it snake_case.
  'Literal[value="subscription_status"]',
];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  //
  // Every generated pattern is written `**/…` rather than `…`. A bare pattern
  // is anchored to this config's directory, so `.next/**` ignores the build
  // output here and nowhere else — and a git worktree under `.claude/worktrees`
  // carries its own `.next`, which is how ~36k lint problems from Turbopack
  // chunks once drowned out the real ones. Build output is build output at any
  // depth.
  globalIgnores([
    // Default ignores of eslint-config-next:
    "**/.next/**",
    "**/out/**",
    "**/build/**",
    "**/next-env.d.ts",
    // Not ESLint's job. `**/node_modules/` is an ESLint default and stays one
    // whether or not it is listed here; it is spelled out so that the set of
    // things this command does not read is legible in one place.
    "**/node_modules/**",
    "**/coverage/**",
    "**/test-results/**",
    "**/playwright-report/**",
    "**/.playwright/**",
    // Agent worktrees are whole second checkouts of this repo on another
    // branch. `npm run lint` lints *this* checkout; the worktree lints itself.
    ".claude/worktrees/**",
    // Vendored shadcn, plus the transitions.dev skill's own reference files.
    "components/ui/**",
    ".agents/**",
  ]),
  {
    files: ["app/**/*.{ts,tsx}", "components/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: `Literal[value=/${ARBITRARY_VALUE}/]`,
          message,
        },
        {
          selector: `TemplateElement[value.raw=/${ARBITRARY_VALUE}/]`,
          message,
        },
        ...subscriptionSelectors.map((selector) => ({
          selector,
          message: subscriptionMessage,
        })),
      ],
    },
  },
  {
    // The boundary itself, and the schema that declares the column. Everything
    // else in the repo goes through canAccess().
    files: ["lib/entitlement/**/*.{ts,tsx}", "lib/db/schema/**/*.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: `Literal[value=/${ARBITRARY_VALUE}/]`,
          message,
        },
        {
          selector: `TemplateElement[value.raw=/${ARBITRARY_VALUE}/]`,
          message,
        },
      ],
    },
  },
]);

export default eslintConfig;
