import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * Arbitrary Tailwind *values* — `bg-[#0af]`, `p-[13px]`, `text-[11px]` — are
 * the hole in a token system. The two-layer design in app/globals.css already
 * makes the raw colour ramps unreachable by keeping them out of `@theme`, but
 * nothing stops someone typing a literal. This closes that.
 *
 * Scoped deliberately:
 *
 * - **Only design properties.** The prefixes below are the ones that carry
 *   colour, spacing and type. Structural escapes stay legal, because they are
 *   not design decisions and have no token to reach for: `transition-[...]` is
 *   a property list, `grid-cols-[repeat(...)]` is a layout algorithm,
 *   `content-['·']` is a string, and `data-[state=open]:` is a variant.
 * - **Arbitrary values, not arbitrary variants.** The negative lookahead on
 *   `:` is what separates `bg-[#0af]` from `data-[state=open]:bg-primary`.
 * - **Our code only.** `components/ui/**` is vendored shadcn, regenerated by
 *   `shadcn add`, and full of legitimate internals like
 *   `h-[calc(100%-1px)]`. Linting it would mean either a permanently failing
 *   build or a fork we have to maintain by hand.
 *
 * If a value here has no token, the fix is to add a role or a scale step in
 * globals.css — not to reach past this rule.
 */
const DESIGN_PREFIXES = [
  "text",
  "bg",
  "border",
  "rounded",
  "shadow",
  "leading",
  "tracking",
  "font",
  "p",
  "px",
  "py",
  "pt",
  "pb",
  "pl",
  "pr",
  "m",
  "mx",
  "my",
  "mt",
  "mb",
  "ml",
  "mr",
  "w",
  "h",
  "size",
  "min-w",
  "min-h",
  "max-w",
  "max-h",
  "gap",
  "top",
  "bottom",
  "left",
  "right",
  "inset",
  "fill",
  "stroke",
  "opacity",
  "duration",
  "ease",
].join("|");

// `(?!:)` keeps arbitrary variants (`data-[state=open]:`) legal; only values
// are matched.
//
// Escaping is single-level on purpose: esquery reads the regex source straight
// out of the selector string, so `\\s` here becomes `\s` in the pattern. An
// extra pair — the obvious first guess — compiles to a literal backslash and
// the rule then silently matches nothing.
const ARBITRARY_VALUE = `(^|\\s)-?(${DESIGN_PREFIXES})-\\[[^\\]]+\\](?!:)`;

const message =
  "Arbitrary Tailwind value. Use a design token — see docs/design-system.md. " +
  "If no token fits, add a semantic role or scale step in app/globals.css " +
  "rather than reaching past the token layer.";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored shadcn, plus the transitions.dev skill's own reference files.
    "components/ui/**",
    ".agents/**",
  ]),
  {
    files: ["app/**/*.{ts,tsx}", "components/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: `Literal[value=/${ARBITRARY_VALUE}/]`,
          message,
        },
        {
          selector: `TemplateElement[value.raw=/${ARBITRARY_VALUE}/]`,
          message,
        },
      ],
    },
  },
]);

export default eslintConfig;
